/**
 * The Question Bowl — the deck.
 *
 * `baseQuestions` is the original deck and is canonical: don't edit it.
 * `expansionQuestions` layers on top, each tagged with a category.
 * `questions` is the flat list the app plays — its shape is unchanged, so the
 * deck logic and UI don't know any of this structure exists.
 */

export type Category =
  | 'Warm-up'
  | 'Personal'
  | 'Messy'
  | 'Dating'
  | 'Risqué'
  | 'Challenge'

export type Expansion = {
  text: string
  category: Category
}

/* ------------------------------------------------------------------ base --- */

/** The original 114. Canonical — do not edit, reword, or reorder. */
export const baseQuestions: string[] = [
  "Describe a time or times when you feel very connected with yourself.",
  "Describe a time you were uncomfortable being alone.",
  "Describe a time you were mean to yourself.",
  "Share something people might not know about you. Maybe something you do at work or with family that people aren’t aware of.",
  "Describe your relationship to the contradicting human needs of: togetherness, separateness, security, freedom, surrender, autonomy.",
  "Dido has a famous song with the lyrics, “No love without freedom, no freedom without love.” Make a personal connection to this quote, or describe a time in your life when you feel this applied.",
  "“Love is the extremely difficult realization that something other than oneself is real.” — Iris Murdoch. Make a personal connection to this quote and share, or describe a time when you connected to this idea.",
  "Describe a time you ended a relationship. (Work, friend, romantic.)",
  "Describe a time a relationship was easy, flowy, and organic. Describe a time you had to work hard at a relationship.",
  "Describe an experience you had with the tension between tradition and newness.",
  "If you could snap your fingers and eliminate one thing from the planet, what would it be? (Except pain, suffering, death, war.) What would you add more of to the world?",
  "If you could eliminate gossip, would you?",
  "Would you rather ask someone out on a date or to hang out, or be asked out? (Friend, romance, etc.) Why?",
  "If you could make sure all children understood one thing, what would it be?",
  "If you could change the behavior of people, what would be one thing you would change?",
  "If you could change the way society views one thing, what would it be?",
  "Say out loud and fill in the blank: “I am amazing at ________.”",
  "What is an adage, mantra, saying, or quote you find meaningful?",
  "This is an acting card. Be very, very dramatic. With great drama and fanfare say, “I’m sorry. I can’t! I just can’t!” and dramatically discard the card.",
  "What is a misconception you think people have about you?",
  "What is a misconception you held for a very long time?",
  "Forgive someone else for something. Can be recent or from years ago. Say it out loud.",
  "Forgive yourself for something. Can be recent or from years ago. Say it out loud.",
  "What is a lesson that took you a really long time to learn?",
  "When you were a child, what is something you absolutely loved doing?",
  "Categories!",
  "What is a role you would like to play more in a relationship? (Work, friend, romantic.)",
  "What is a role you played in a relationship (work, friend, romantic) that you didn’t enjoy or sought to change?",
  "Describe a quality of “sameness” you look for in relationships, and a quality of “difference” you look for in relationships.",
  "What are 3 expectations you have for a relationship? Choose whether it’s a friend, romantic, business, or other.",
  "Did you have an open-door family vibe or a closed-door family vibe growing up?",
  "What was something you felt like you had too much of growing up, and too little of growing up?",
  "What is a story you often tell about yourself? What is a story you often tell about yourself that you would like to let go of?",
  "Were you educated in your youth that self-reliance is crucial, or were you taught to depend on others?",
  "What misinformation from your youth have you had to unlearn? Or do you want to unlearn?",
  "What is a piece of misinformation you often see other people falling for?",
  "Describe a time you were a people pleaser. What would you do differently now?",
  "When was a time you reacted in a way you wish you didn’t? What would you change?",
  "When was a time you made an assumption that turned out to be wrong?",
  "Describe a miscommunication that you experienced.",
  "When was a time you gave up but feel you shouldn’t have?",
  "Describe a firm boundary you have. Describe a porous boundary you have.",
  "Describe a time someone had power over you. Describe a time you had power over someone.",
  "Describe a time when you have given power to someone.",
  "Describe a time when you felt you had very little agency. Describe a time when you felt you had a lot of agency.",
  "Describe a difficult conversation you had with someone.",
  "Describe a time you had a conflict that got out of control. Describe a time you had a healthy conflict.",
  "Describe a time you avoided something.",
  "Describe a time you were confrontational.",
  "Describe a time you trusted someone and were let down.",
  "Describe a time you trusted someone and it worked out well.",
  "Describe a time you were betrayed.",
  "Describe a time you betrayed someone.",
  "Describe a relationship that ended and you had to let go.",
  "Describe a relationship you’ve had that is generative, erotic, vibrant.",
  "Describe a relationship you’ve had that felt dead and/or sapped your energy.",
  "What’s a dream you never shared?",
  "What’s a rule you secretly love to break?",
  "What’s a lie you’re tempted to tell about yourself?",
  "What did you learn about love or relationships from your parents?",
  "Never Have I Ever",
  "What makes you trust someone? What makes you distrust someone?",
  "Name a piece of art, movie, TV show, or play that you loved and think everyone should see.",
  "Give a compliment to the person to your right.",
  "Give an A grade to someone at the table for something they’ve done or said recently. Explain why.",
  "Give a rose and a thorn for the day, week, or month.",
  "Say something you’re grateful for.",
  "Say an intention or goal for the day, week, month, or year.",
  "Who would you be starstruck to see?",
  "What is something you wish you were more intentional about?",
  "What are three lessons or values you would want to instill upon your children (if you had children)?",
  "What is a life hack or productivity tip that has helped you a lot?",
  "What is a great piece of advice someone shared with you?",
  "What is an important lesson you learned from a prior relationship?",
  "What is something in your life you thought would never change but surprisingly did?",
  "Describe an ideal day.",
  "Name a place you’ve traveled to and would go again. Name a place you would avoid.",
  "What’s been your biggest adventure?",
  "What is something new sexually you would like to experience?",
  "What is one of the most challenging emotions for you to experience?",
  "When do you feel most present? Like you’re a child at play.",
  "What would you say makes you not the easiest person to live with?",
  "Describe a time when you changed your mind.",
  "What would you do if you had a different career?",
  "Were you raised for autonomy or raised for loyalty?",
  "What is something you wish you had known or been told as a child?",
  "What is one of the lessons learned from a heartbreak?",
  "What is a conversation that you need to have with yourself?",
  "What is a habit you would like to stop? What is a habit you would like to start?",
  "When did you know you were no longer a child?",
  "What is a tradition you love and wish to continue?",
  "What is the relationship legacy from your own family of origin that you want to keep?",
  "What is an aspect from your relationship culture that you’re set on changing?",
  "What’s a challenge that you have successfully faced, and how have you handled it?",
  "Name a risk you took that paid off.",
  "Name a risk that you’ve taken and learned from.",
  "Name someone who has inspired you, and how.",
  "Name a time you had an “aha” moment that led you to make a big change.",
  "Would you rather care for someone or be cared for? Why?",
  "What’s something you like or dislike that most other people don’t?",
  "What is your ______________ ____________ experience?",
  "Marry, ____________, kill . . . The person to your left chooses the 3.",
  "What is your ideal frequency for having _________?",
  "What’s something __________ you like that most other people don’t?",
  "What is a relationship must for you? Romantic or otherwise.",
  "What is a ____________ must for you?",
  "What is a major ___________ turn-off?",
  "What is a major relationship red flag for you?",
  "Why are you such a __________?",
  "What is one _______________ experience or act you would like to try?",
  "What is one _______________ experience or act you have done but don’t want to do again?",
  "M, F, K: Pudding, Pickles, Porridge.",
  "M, F, K: The person to your right chooses the 3.",
  "M, F, K: The person across from you chooses the 3.",
]

/* ------------------------------------------------------------- expansion --- */

/**
 * The expansion deck. Two exact duplicates of base questions were dropped
 * during the audit — see README. Near-duplicates are still here, flagged in
 * the audit but deliberately left in play pending review.
 */
export const expansionQuestions: Expansion[] = [
  /* -- Warm-up ----------------------------------------------------------- */
  { category: 'Warm-up', text: "What’s the weirdest compliment you’ve ever received?" },
  { category: 'Warm-up', text: "Which person here do you think would survive longest on a deserted island?" },
  { category: 'Warm-up', text: "What’s a completely useless talent you’re oddly proud of?" },
  { category: 'Warm-up', text: "If your life had a warning label, what would it say?" },
  { category: 'Warm-up', text: "Which person here would make the best cult leader?" },
  { category: 'Warm-up', text: "What’s the most ridiculous purchase you’ve ever justified?" },
  { category: 'Warm-up', text: "If you had to swap lives with someone here for a week, who would it be?" },
  { category: 'Warm-up', text: "What’s your most irrational fear?" },
  { category: 'Warm-up', text: "What TV family would you want to join?" },
  { category: 'Warm-up', text: "What’s the funniest lie you’ve ever told?" },
  { category: 'Warm-up', text: "What’s one thing everyone should experience once?" },
  { category: 'Warm-up', text: "What’s your most controversial food opinion?" },
  { category: 'Warm-up', text: "What would your autobiography be called?" },
  { category: 'Warm-up', text: "What’s something you’ve pretended to know about?" },
  { category: 'Warm-up', text: "Which person here would be the hardest to date?" },
  { category: 'Warm-up', text: "What’s a tiny hill you’d die on?" },
  { category: 'Warm-up', text: "If you could relive one day, which would it be?" },
  { category: 'Warm-up', text: "What’s something you secretly think you’re excellent at?" },
  { category: 'Warm-up', text: "If your phone wallpaper had to be explained, what would the story be?" },

  /* -- Personal ---------------------------------------------------------- */
  { category: 'Personal', text: "When was the last time you changed your mind about something important?" },
  { category: 'Personal', text: "What’s something you’ve never apologized for but probably should?" },
  { category: 'Personal', text: "What’s one thing you wish people understood about you?" },
  { category: 'Personal', text: "What’s your biggest relationship green flag?" },
  { category: 'Personal', text: "What’s your biggest relationship red flag?" },
  { category: 'Personal', text: "When do you feel most attractive?" },
  { category: 'Personal', text: "What’s the nicest thing an ex ever did for you?" },
  { category: 'Personal', text: "Who knows you better than anyone?" },
  { category: 'Personal', text: "What’s something you’ve outgrown?" },
  { category: 'Personal', text: "When do you feel most like yourself?" },
  { category: 'Personal', text: "What’s something you miss from childhood?" },
  { category: 'Personal', text: "What’s something you’ve never admitted to your parents?" },
  { category: 'Personal', text: "What’s one insecurity you’ve mostly overcome?" },
  { category: 'Personal', text: "What’s your love language — even if you hate the phrase?" },
  { category: 'Personal', text: "What’s something you’ve forgiven that surprised you?" },
  { category: 'Personal', text: "What’s your biggest “what if?”" },
  { category: 'Personal', text: "What’s something you’re currently working on in yourself?" },
  { category: 'Personal', text: "What’s one compliment you’ll never forget?" },
  { category: 'Personal', text: "What’s something you hope is true five years from now?" },

  /* -- Messy ------------------------------------------------------------- */
  { category: 'Messy', text: "What’s the pettiest thing you’ve ever done?" },
  { category: 'Messy', text: "Have you ever accidentally ruined someone’s relationship?" },
  { category: 'Messy', text: "What’s the most awkward text you’ve sent to the wrong person?" },
  { category: 'Messy', text: "What’s the worst first impression you’ve ever made?" },
  { category: 'Messy', text: "Have you ever pretended not to recognize someone?" },
  { category: 'Messy', text: "What’s your most embarrassing drunk story?" },
  { category: 'Messy', text: "What’s something you’ve stolen — even accidentally?" },
  { category: 'Messy', text: "Have you ever faked being sick to avoid someone?" },
  { category: 'Messy', text: "What’s your biggest social regret?" },
  { category: 'Messy', text: "What’s the longest you’ve gone without admitting you were wrong?" },
  { category: 'Messy', text: "What’s the meanest thing you’ve ever said in an argument?" },
  { category: 'Messy', text: "Have you ever ghosted someone you actually liked?" },
  { category: 'Messy', text: "What’s the biggest lie you’ve told that nobody ever discovered?" },
  { category: 'Messy', text: "What’s the most jealous you’ve ever been?" },
  { category: 'Messy', text: "Have you ever sabotaged yourself?" },
  { category: 'Messy', text: "What’s the closest you’ve come to getting arrested?" },
  { category: 'Messy', text: "What’s your worst wedding guest behavior?" },
  { category: 'Messy', text: "What’s the most embarrassing thing someone has caught you doing?" },
  { category: 'Messy', text: "What’s the biggest misunderstanding you’ve ever created?" },
  { category: 'Messy', text: "What’s the hardest you’ve laughed at someone else’s misfortune?" },

  /* -- Dating ------------------------------------------------------------ */
  { category: 'Dating', text: "Which celebrity would immediately make you nervous to flirt with?" },
  { category: 'Dating', text: "What’s the boldest move you’ve made on someone?" },
  { category: 'Dating', text: "Have you ever had a crush on someone in this room?" },
  { category: 'Dating', text: "What’s your biggest turn-on that isn’t physical?" },
  { category: 'Dating', text: "What’s the most attractive quality someone can have?" },
  { category: 'Dating', text: "Have you ever kissed someone you just met?" },
  { category: 'Dating', text: "What’s the most spontaneous romantic thing you’ve ever done?" },
  { category: 'Dating', text: "Have you ever had feelings for someone you absolutely shouldn’t have?" },
  { category: 'Dating', text: "What’s your biggest dating “ick”?" },
  { category: 'Dating', text: "What’s something someone could do that would instantly make you interested?" },
  { category: 'Dating', text: "Have you ever accidentally flirted with the wrong person?" },
  { category: 'Dating', text: "What’s your most memorable first kiss?" },
  { category: 'Dating', text: "What’s the biggest age gap you’ve dated?" },
  { category: 'Dating', text: "Have you ever been caught making out?" },
  { category: 'Dating', text: "What’s your favorite excuse for leaving a bad date?" },
  { category: 'Dating', text: "What’s the most ridiculous reason you’ve liked someone?" },
  { category: 'Dating', text: "Have you ever matched with someone you already knew?" },
  { category: 'Dating', text: "What’s something you’ve always wanted to try on a date?" },
  { category: 'Dating', text: "Have you ever gone on two dates in one day?" },
  { category: 'Dating', text: "What’s your most unforgettable romantic disaster?" },

  /* -- Risqué ------------------------------------------------------------ */
  { category: 'Risqué', text: "What’s the most memorable hookup you’ve ever had, and what made it stick?" },
  { category: 'Risqué', text: "What does your Grindr profile claim about you that isn’t strictly true?" },
  { category: 'Risqué', text: "What’s a kink you were surprised to discover you were into?" },
  { category: 'Risqué', text: "What’s your hard limit — the thing you’ll never be talked into?" },
  { category: 'Risqué', text: "What’s the hottest thing someone has ever said to you in bed?" },
  { category: 'Risqué', text: "What’s the most public place you’ve ever had sex?" },
  { category: 'Risqué', text: "Top, bottom, vers — and has that changed over the years?" },
  { category: 'Risqué', text: "What’s the strangest place you’ve ever met someone for sex?" },
  { category: 'Risqué', text: "What’s a sexual boundary you set that you’re proud of?" },
  { category: 'Risqué', text: "Have you ever used Sniffies? How did that go?" },
  { category: 'Risqué', text: "What’s the biggest gap you’ve encountered between the profile and the person?" },
  { category: 'Risqué', text: "What’s a fantasy you’ve never said out loud to anyone at this table?" },
  { category: 'Risqué', text: "What’s the best sex you’ve ever had, and what made it the best?" },
  { category: 'Risqué', text: "What were you into five years ago that does nothing for you now?" },
  { category: 'Risqué', text: "Tell the story of your first time with a man." },
  { category: 'Risqué', text: "How do you turn someone down when you’re just not interested?" },
  { category: 'Risqué', text: "What’s a sexual insecurity you’ve made peace with?" },
  { category: 'Risqué', text: "What’s the worst hookup you’ve ever had — the one that became a story?" },
  { category: 'Risqué', text: "What’s a physical type you’re into that your friends have never understood?" },
  { category: 'Risqué', text: "Have you ever had sex somewhere you could have been caught? What happened?" },

  /* -- Challenge --------------------------------------------------------- */
  { category: 'Challenge', text: "Let the group choose your phone wallpaper until tomorrow." },
  { category: 'Challenge', text: "Speak in an accent until your next turn." },
  { category: 'Challenge', text: "Swap seats with the person who knows you least." },
  { category: 'Challenge', text: "Attempt 20 push-ups." },
  { category: 'Challenge', text: "Trade one article of clothing with the person to your left." },
  { category: 'Challenge', text: "Do your best impression of another player." },
  { category: 'Challenge', text: "Serenade someone with the chorus of any song." },
  { category: 'Challenge', text: "Let another player style your hair." },
  { category: 'Challenge', text: "Do five yoga poses chosen by the group." },
  { category: 'Challenge', text: "Tell a joke. If nobody laughs, tell another." },
  { category: 'Challenge', text: "Moonwalk — or attempt to." },
  { category: 'Challenge', text: "Hold eye contact with the person across from you for 30 seconds without laughing." },
  { category: 'Challenge', text: "Do your best animal impression until someone guesses it." },
  { category: 'Challenge', text: "Read out the last message you sent on a hookup app." },
  { category: 'Challenge', text: "Let the group write your hookup-app tagline for the next 24 hours." },
  { category: 'Challenge', text: "Text an ex, “I was just thinking about you.” No explanation, no follow-up." },
  { category: 'Challenge', text: "Do your most convincing moan." },
  { category: 'Challenge', text: "Try your best opening line on the person to your right." },
  { category: 'Challenge', text: "Take off one item of clothing. You choose which." },
  { category: 'Challenge', text: "Let the table pick one word to describe you in bed." },
  { category: 'Challenge', text: "Give the person to your left a fifteen-second shoulder massage." },
  { category: 'Challenge', text: "Whisper something filthy to the person on your right. They decide whether to repeat it." },
  { category: 'Challenge', text: "Rank the table by who would be the best kisser. Out loud, with reasons." },
  { category: 'Challenge', text: "Describe your type in three words, then let the table rule on whether that’s really true." },
  { category: 'Challenge', text: "Say the filthiest thing you’ve ever said in bed, in the most romantic voice you can manage." },
]

/* ----------------------------------------------------------------- deck --- */

/** What the app plays. Same flat shape it has always been. */
export const questions: string[] = [
  ...baseQuestions,
  ...expansionQuestions.map((q) => q.text),
]
