/**
 * Question Bowl — the deck.
 * One string per card. Order does not matter; the app shuffles.
 */
export const questions: string[] = [
  "Describe a time or times when you feel very connected with yourself.",
  "Describe a time you were uncomfortable being alone.",
  "Describe a time you were mean to yourself.",
  "Share something people might not know about you. Maybe something you do at work or with family that people aren’t aware of.",
  "Describe your relationship to the contradicting human needs of: togetherness, separateness, security, freedom, surrender, autonomy.",
  "Dido has a famous song with the lyrics, “No love without freedom, no freedom without love.” Make a personal connection to this quote, or describe a time in your life when you feel this applied.",
  "“Love is the extremely difficult realization that something other than oneself is real.” — Iris Murdoch. Make a personal connection to this quote and share, or describe a time when you connected to this idea.",
  "Describe a time you ended a relationship. (Work, friend, romantic.)",
  "Describe a time a relationship was easy, flowy, and organic. Describe a time you had to work hard at a relationship.",
  "Describe an experience you had with the tension between tradition and newness.",
  "If you could snap your fingers and eliminate one thing from the planet, what would it be? (Except pain, suffering, death, war.) What would you add more of to the world?",
  "If you could eliminate gossip, would you?",
  "Would you rather ask someone out on a date or to hang out, or be asked out? (Friend, romance, etc.) Why?",
  "If you could make sure all children understood one thing, what would it be?",
  "If you could change the behavior of people, what would be one thing you would change?",
  "If you could change the way society views one thing, what would it be?",
  "Say out loud and fill in the blank: “I am amazing at ________.”",
  "What is an adage, mantra, saying, or quote you find meaningful?",
  "This is an acting card. Be very, very dramatic. With great drama and fanfare say, “I’m sorry. I can’t! I just can’t!” and dramatically discard the card.",
  "What is a misconception you think people have about you?",
  "What is a misconception you held for a very long time?",
  "Forgive someone else for something. Can be recent or from years ago. Say it out loud.",
  "Forgive yourself for something. Can be recent or from years ago. Say it out loud.",
  "What is a lesson that took you a really long time to learn?",
  "When you were a child, what is something you absolutely loved doing?",
  "Categories!",
  "What is a role you would like to play more in a relationship? (Work, friend, romantic.)",
  "What is a role you played in a relationship (work, friend, romantic) that you didn’t enjoy or sought to change?",
  "Describe a quality of “sameness” you look for in relationships, and a quality of “difference” you look for in relationships.",
  "What are 3 expectations you have for a relationship? Choose whether it’s a friend, romantic, business, or other.",
  "Did you have an open-door family vibe or a closed-door family vibe growing up?",
  "What was something you felt like you had too much of growing up, and too little of growing up?",
  "What is a story you often tell about yourself? What is a story you often tell about yourself that you would like to let go of?",
  "Were you educated in your youth that self-reliance is crucial, or were you taught to depend on others?",
  "What misinformation from your youth have you had to unlearn? Or do you want to unlearn?",
  "What is a piece of misinformation you often see other people falling for?",
  "Describe a time you were a people pleaser. What would you do differently now?",
  "When was a time you reacted in a way you wish you didn’t? What would you change?",
  "When was a time you made an assumption that turned out to be wrong?",
  "Describe a miscommunication that you experienced.",
  "When was a time you gave up but feel you shouldn’t have?",
  "Describe a firm boundary you have. Describe a porous boundary you have.",
  "Describe a time someone had power over you. Describe a time you had power over someone.",
  "Describe a time when you have given power to someone.",
  "Describe a time when you felt you had very little agency. Describe a time when you felt you had a lot of agency.",
  "Describe a difficult conversation you had with someone.",
  "Describe a time you had a conflict that got out of control. Describe a time you had a healthy conflict.",
  "Describe a time you avoided something.",
  "Describe a time you were confrontational.",
  "Describe a time you trusted someone and were let down.",
  "Describe a time you trusted someone and it worked out well.",
  "Describe a time you were betrayed.",
  "Describe a time you betrayed someone.",
  "Describe a relationship that ended and you had to let go.",
  "Describe a relationship you’ve had that is generative, erotic, vibrant.",
  "Describe a relationship you’ve had that felt dead and/or sapped your energy.",
  "What’s a dream you never shared?",
  "What’s a rule you secretly love to break?",
  "What’s a lie you’re tempted to tell about yourself?",
  "What did you learn about love or relationships from your parents?",
  "Never Have I Ever",
  "What makes you trust someone? What makes you distrust someone?",
  "Name a piece of art, movie, TV show, or play that you loved and think everyone should see.",
  "Give a compliment to the person to your right.",
  "Give an A grade to someone at the table for something they’ve done or said recently. Explain why.",
  "Give a rose and a thorn for the day, week, or month.",
  "Say something you’re grateful for.",
  "Say an intention or goal for the day, week, month, or year.",
  "Who would you be starstruck to see?",
  "What is something you wish you were more intentional about?",
  "What are three lessons or values you would want to instill upon your children (if you had children)?",
  "What is a life hack or productivity tip that has helped you a lot?",
  "What is a great piece of advice someone shared with you?",
  "What is an important lesson you learned from a prior relationship?",
  "What is something in your life you thought would never change but surprisingly did?",
  "Describe an ideal day.",
  "Name a place you’ve traveled to and would go again. Name a place you would avoid.",
  "What’s been your biggest adventure?",
  "What is something new sexually you would like to experience?",
  "What is one of the most challenging emotions for you to experience?",
  "When do you feel most present? Like you’re a child at play.",
  "What would you say makes you not the easiest person to live with?",
  "Describe a time when you changed your mind.",
  "What would you do if you had a different career?",
  "Were you raised for autonomy or raised for loyalty?",
  "What is something you wish you had known or been told as a child?",
  "What is one of the lessons learned from a heartbreak?",
  "What is a conversation that you need to have with yourself?",
  "What is a habit you would like to stop? What is a habit you would like to start?",
  "When did you know you were no longer a child?",
  "What is a tradition you love and wish to continue?",
  "What is the relationship legacy from your own family of origin that you want to keep?",
  "What is an aspect from your relationship culture that you’re set on changing?",
  "What’s a challenge that you have successfully faced, and how have you handled it?",
  "Name a risk you took that paid off.",
  "Name a risk that you’ve taken and learned from.",
  "Name someone who has inspired you, and how.",
  "Name a time you had an “aha” moment that led you to make a big change.",
  "Would you rather care for someone or be cared for? Why?",
  "What’s something you like or dislike that most other people don’t?",
  "What is your ______________ ____________ experience?",
  "Marry, ____________, kill . . . The person to your left chooses the 3.",
  "What is your ideal frequency for having _________?",
  "What’s something __________ you like that most other people don’t?",
  "What is a relationship must for you? Romantic or otherwise.",
  "What is a ____________ must for you?",
  "What is a major ___________ turn-off?",
  "What is a major relationship red flag for you?",
  "Why are you such a __________?",
  "What is one _______________ experience or act you would like to try?",
  "What is one _______________ experience or act you have done but don’t want to do again?",
  "M, F, K: Pudding, Pickles, Porridge.",
  "M, F, K: The person to your right chooses the 3.",
  "M, F, K: The person across from you chooses the 3.",
]
